### ISSUE TITLE
Freeing memory failed in example code 

### ISSUE THREAD

**Issue by cheenng** [tidwall/hashmap.c#10]
Hi @tidwall 

thank you for your work and i would like to use your implementation in my project. However, I encoutered a problem which eludes me:

I ran the example code in README.md with debug configuratioin in eclipse and it crashes at the last step "hmfree(map);" in hashmap_free. More information in screenshot below.
![Screenshot 2021-03-22 171956](https://user-images.githubusercontent.com/33980814/112023172-47da1680-8b33-11eb-9413-dca9b9123106.png)

I ran it as well in console, got a warning about heap block, please see screenshot below:
![Screenshot 2021-03-22 173211](https://user-images.githubusercontent.com/33980814/112024831-ddc27100-8b34-11eb-9475-f9a21da7fe19.png)

Could you reproduce this issue?
I am using gcc4.9.1 of MinGW. Looking forward to your reply. Thank you!

Best regards
Yuan

**Comment by tidwall** [comment]
Thank you very much for reporting this issue.
