### ISSUE TITLE
`key` arg of `hashmap_get` is not const

### ISSUE THREAD

**Issue by scossu** [tidwall/hashmap.c#12]
From https://github.com/tidwall/hashmap.c/blob/master/hashmap.c#L278-L296 I see that the only use of the `key` parameter is to pass it to the compare and hash functions, both of which accept a `const void *`. Is there a reason for `hashmap_get` not to accept a `const void` too, thus avoiding discarding a possible `const` qualifier in the caller? Thanks.

**Comment by tidwall** [comment]
You are right. This should probably be a `const void *`.

**Comment by tidwall** [comment]
I'm closing this issue because you fixed it in #13. Thanks!
