### ISSUE TITLE
[QUESTION] Bit-packing and subsequent shifting

### ISSUE THREAD

**Issue by levouh** [tidwall/hashmap.c#14]
Looking over the code a bit, I have a few questions. The main `struct bucket` is declared as such:

```c
struct bucket {
    uint64_t hash:48;
    uint64_t dib:16;
};
```

where we are bit-packing such for a given "bucket", the hash ends up being 48 bits, and the "distance in bucket" (effectively a measure of wealth w/ Robin Hood probing) can be 16 bits. Since each is a `uint64_t`, we have `48 + 16`, so we are effectively "taking up" the space of one `uint64_t` but storing two distinct values there. Cool.

Later when calculating the hash, we do:

```c
static uint64_t get_hash(struct hashmap *map, const void *key) {
    return map->hash(key, map->seed0, map->seed1) << 16 >> 16;
}
```

focusing specifically on the `<< 16 >> 16` part. Is this to "trim off" the 16 bits that we don't _need_ from the `uint64_t` such that it aligns with the bit-packing? Is this reliable across different compiler versions (the implementation of bit-packing is completely compiler-dependent, while it should yield a _similar_ result bit-packing wise)?

---

Separately, what is the point of the first part of this conditional?

```c
            if (map->nbuckets > map->cap && map->count <= map->shrinkat) {
                // Ignore the return value. It's ok for the resize operation to
                // fail to allocate enough memory because a shrink operation
                // does not change the integrity of the data.
                resize(map, map->nbuckets/2);
            }
```

When can `map->buckets` be greater than `map->cap`?

**Comment by tidwall** [comment]
> Is this to "trim off" the 16 bits 

Yes, and I don't know how compiler compatible the `<< 16 >> 16` operation is or isn't. Clang and GCC handle it fine, but perhaps `& 0xFFFFFFFFFFFF` should work better.

> When can map->buckets be greater than map->cap?

The following resize operation will shrink the hashmap. But I don't want the number of buckets to ever fall below the capacity that the user requests when calling `hashmap_new`.
