### ISSUE TITLE
Is this hashmap thread-safe?

### ISSUE THREAD

**Issue by piaodazhu** [tidwall/hashmap.c#22]
Very user-friendly and powerful hash map library! Is this hash map thread-safe? I want to insert and delete items in different threads, are there any risk that the program will crash? 
Since I haven't find 'mutex/lock/atomic' in the source, I guess it probably won't work well in such condition. If so, does anyone have idea about achieving thread-safety for this hash map? I'm glad to create a pull request after I implement this part. :)

**Comment by gyrovorbis** [comment]
Yeah, I'm using it in a multithreaded environment. No, it's not inherently thread-safe, however you just put a mutex around accessing it. Lock it before calling a set or get and unlock it after. I've had a very easy time making it thread-safe.
