### ISSUE TITLE
Complete misses with keys > 256 bytes?

### ISSUE THREAD

**Issue by trojanfoe** [tidwall/hashmap.c#23]
I think I have noticed misses with keys greater than 256 bytes in length.

- When I say "misses" I mean being unable to find existing entries with `hashmap_get()` or `hashmap_delete()`.
- The keys are filenames using `WCHAR`s under Windows 10.
- I have tried both the SIP and the Murmur3 hash functions and get roughly the same results.
- I get fewer misses with using SIP and setting the seeds both to `0`, rather than using a random number.

Any help with issue would be much appreciated.

**Comment by tidwall** [comment]
Could you provide example code? That would help with diagnosing the issues.

**Comment by trojanfoe** [comment]
Yeah I'll get on that, thanks.

**Comment by trojanfoe** [comment]
I found the issue within my _compare_ function implementation so there is no issue with your code!  Sorry to waste your time and thanks for your efforts!
