### ISSUE TITLE
ttlHashMap based on this project to support expiration

### ISSUE THREAD

**Issue by piaodazhu** [tidwall/hashmap.c#24]
This user-friendly and powerful hash map library helps me a lot, and I have an idea about it.

One day, I used hashmap.c to replace hiredis as a lightweight cache. I found that,  in that condition, hashmap.c is much faster than hiredis sync API, and is much simpler than hiredis async API. However, it does not support expiration. So, I wrote a wrapper based on hashmap.c: [ttlHashmap](https://github.com/piaodazhu/ttlHashMap). It supports expiration and is thread-safe.

I'm glad to create a pull request or something else to contribute to this project.

**Comment by tidwall** [comment]
Hi piaodazhu, 

Nice project and thanks for the suggestion. But, adding TTL functionality directly into this library is out of scope. It's my desire to keep this library as slim as possible so that it can be used as a building block for projects like yours.

**Comment by piaodazhu** [comment]
Yes, it is better to keep it slim. :)
