### ISSUE TITLE
Please, add tests (if any) and benchmark files

### ISSUE THREAD

**Issue by fregate** [tidwall/hashmap.c#28]
In readme you have benchmarks, so is it possible to add it to repo?

**Comment by tidwall** [comment]
Benchmarks and tests are currently included in the hashmap.c file.

https://github.com/tidwall/hashmap.c/blob/603792ba74d987f37439ecd531faa90ec2c10b2f/hashmap.c#L620

You can run the following commands for results. 

```c
//==============================================================================
// TESTS AND BENCHMARKS
// $ cc -DHASHMAP_TEST hashmap.c && ./a.out              # run tests
// $ cc -DHASHMAP_TEST -O3 hashmap.c && BENCH=1 ./a.out  # run benchmarks
//==============================================================================
```

**Comment by fregate** [comment]
Yes, I see. Sorry
