### ISSUE TITLE
RFE: Add meson build

### ISSUE THREAD

**Issue by engelmi** [tidwall/hashmap.c#32]
### Feature Request

I'd like to request to add [meson](mesonbuild.com/) as a build system for `hashmap.c` to easily integrate it into other (meson) projects.
 
If this RFE is considered to be an improvement for the project, I'd be happy to provide a PR for it. 

### Background

In the project [hirte](https://github.com/containers/hirte/) we are currently using a copy of `hashmap.c`. However, we want to be able to easily upgrade the library in our project if a new `hashmap.c` version is released. Since we are using meson as a build system we consider integrating it as a [meson subproject](https://mesonbuild.com/Subprojects.html) via a `wrap-git`. This, however, only works for projects using meson (ignoring some workarounds).

**Comment by dougsland** [comment]
+1

**Comment by dougsland** [comment]
@tidwall Hey Josh, could you please review this one and give as an ack? 

Thanks!

**Comment by tidwall** [comment]
Adding the Meson build system is outside of the scope of this project.

**Comment by dougsland** [comment]
@tidwall oh no, can we add least send a PR and help maintain the meson build? The only required action is review/merge. We would prefer to stay upstream as much as possible and skip forks.

Thanks!

**Comment by engelmi** [comment]
> Adding the Meson build system is outside of the scope of this project.

That is unfortunate. Although I can understand your argument, I think this project would benefit from providing its source via a build system like meson to ease the integration into using projects and stay up to date. 
Closing this issue.
