### ISSUE TITLE
Key and value not separate in the hashmap_set function

### ISSUE THREAD

**Issue by HeavenlyAwe** [tidwall/hashmap.c#33]
Really nice implementation of a hashmap in C!

The `get_hash` function should always be called with the key as second argument, but in the setter you are using the item itself. Just add another input parameter to the setter to provide the key along with the value. This key parameter should then be passed on to the `get_hash` function.

Biggest issue with the current implementation is that you already have to know the item to be able to poll it from the map, making the call to the map redundant.

**Comment by HeavenlyAwe** [comment]
Thanks for sharing the wrapper and for explaining more about the `get_hash` implementation.

Sorry for not being clear enough, but my concern was more directed at the prototype/function declaration of the `hashmap_set` function.
https://github.com/tidwall/hashmap.c/blob/84d0d3bf75f297443a5069b801ea13d93ee05e0a/hashmap.c#L300-L302
As here the item is used both as value and key (passed to the `get_hash` function). This means that when I want to retrieve the value by using the `hashmap_get` function I will need a reference to the value to access it. It's of course possible that I'm missing this piece in your answer?

The `get_hash` function is IMO correctly implemented to make unique hashes of the provided data. However, hashmaps in other libraries use both key and value pairs in the setters and keys in the getters. It's completely possible that I am missing some crucial point regarding the current implementation?

**Comment by HeavenlyAwe** [comment]
I believe the `hashmap_set` function should look like this:

```
const void *hashmap_set(struct hashmap *map, const void *key, const void *item) { 
     return hashmap_set_with_hash(map, item, get_hash(map, key)); 
 } 

```

**Comment by HeavenlyAwe** [comment]
I read this part again and see that you actually addressed my question in the last sentence.

> My library offers an STL-style C API around the hashmap back-end and then above that offers a `HashSet` and a `HashMap` C++20 layer with the full STL interface. The HashSet keeps each key/value as a single combined item structure as with the vanilla API, but the `HashMap` level adds an adapter that breaks out the key and value into two different types (which are then packed into a single item), and probably works more the way you're used to.

I still believe that this library could benefit from adding an explicit setter using the key and value separately to avoid extra boilerplate code setting up key and value bundles. The HashSet use case had eluded me prior to your comment, and I had never before realized how close the implementations of hashmaps and hashsets are!

**Comment by I-am-Le** [comment]
....  is this the function you're looking for?

https://github.com/tidwall/hashmap.c/blob/84d0d3bf75f297443a5069b801ea13d93ee05e0a/hashmap.c#L247-L251

**Comment by HeavenlyAwe** [comment]
No, not really, the function you suggest would be used by the function I'm missing. The suggested function needs a hash, and the hash is computed from the key. But that's -- at least to me the confusing part -- in the setter we use the item itself instead of a key to generate the hash.

I understand that we can bundle the key within the item and only calculate the hash for that binary part of the key, like gyrovorbis said. However, this requires wrappers and extra boilerplate code around this library, which I'm not really needing, as the library is self sufficient based on the provided main function.

In the benchmark function, one can see that the library only uses the item itself when setting the elements in the different maps. It doesn't set up any keys in the items, so it is impossible to access the item itself from the map in the examples without having a reference to the stored item itself (making the hashmap_get() calls rather redundant). It works in the benchmarks because it technically measures the speed of setting and getting values, the tests don't have to care about who provides the keys.

https://github.com/tidwall/hashmap.c/blob/84d0d3bf75f297443a5069b801ea13d93ee05e0a/hashmap.c#L1054-L115

A more practical example to my question: If I would want to extend the benchmarks with a map with integer keys pointing at doubles, how do I do that in the same manner as the existing maps? I'd like to generate the double data as an array (like it is done now), and use the enumerator in the loop as key. That way I don't have to know the values of the doubles to get them.

**Comment by HeavenlyAwe** [comment]
Sorry for being slow, but I actually think I'm starting to see what @gyrovorbis was trying to explain about the "unconventional" way of storing the key as a part of the item. I'll have to look further into how I can adapt this to my own project, thanks for the nice feedback and the attempts of getting me in the right direction!

The functionality I'm interested has to be implemented in a wrapper. I think I'll close this issue as @gyrovorbis answer actually presented me with the solution I had a hard time grasping!
