### ISSUE TITLE
Potential bug in map->spare usage (used both as struct bucket and stored item)

### ISSUE THREAD

**Issue by HeavenlyAwe** [tidwall/hashmap.c#34]
In the initialize function `map->spare` is initialized to have `sizeof(hashmap) + 2 * bucketsz`

But it is used both as `struct bucket` and as the items stored in the buckets in the setter and getter.

https://github.com/tidwall/hashmap.c/blob/84d0d3bf75f297443a5069b801ea13d93ee05e0a/hashmap.c#L280-L290
https://github.com/tidwall/hashmap.c/blob/84d0d3bf75f297443a5069b801ea13d93ee05e0a/hashmap.c#L361

As long as `elsize` is smaller than `bucketsz` this shouldn't be a problem.

**Comment by tidwall** [comment]
This is by design. It's not a bug, nor even potentially a bug.

The spare field is large enough to hold a bucket or an item, and a bucket size is always larger than an item size.

https://github.com/tidwall/hashmap.c/blob/84d0d3bf75f297443a5069b801ea13d93ee05e0a/hashmap.c#L105

**Comment by HeavenlyAwe** [comment]
Thanks for the explanation. I wasn't completely sure prior to this explanation.
