### ISSUE TITLE
thread safe concern

### ISSUE THREAD

**Issue by 979357361** [tidwall/hashmap.c#37]
I noticed that iter is not thread safe, so i worry about other API
Is it thread safe while multi-thread doing get/set/delete？
For example,  item returned by set and detele are all from map->spare, while a later set overwrite the earlier item in map->spare？
what will happen if A call get and B delete it the same time?

thank you for your time and patience~

**Comment by tidwall** [comment]
> Is it thread safe while multi-thread doing get/set/delete?

No, this library will need a lock of some kind to safely use mutable operations in multiple threads.

For immutable operations like get, iter, scan, and count, those don't modify the hashmap and can be safely used in multiple threads. 

But as soon as you use mutable like set and delete in multiple threads, then you must use a lock for ALL operations.

> What will happen if A call get and B delete it the same time?

Your hashmap may get corrupted. 
You should use a lock, such as a mutex, rwlock, or spinlock. 

For example, let's say you have two threads. One reader and one writer.

**Thread 1** (reader)

```c
lock(READ)
const void *item = hashmap_get(map, key);
// It's safe to do something with item here.
unlock(READ);
// UNSAFE to use item now.
```

**Thread 2** (writer)

```c
lock(WRITE);
const void *old_item = hashmap_set(map, item);
// It's safe to do something with old_item here.
unlock(WRITE);
// UNSAFE to use old_item now.
```

**Comment by 979357361** [comment]
Thank you, I got you, maybe I need to find another C map lib.
I have multiple threads (32 for example) visit the map, most time they do get, but set and delete are called sometimes, as for now I use no lock and I planned to set a lock for delete/set and iter. Its lucky that it runs without any problems so far, there may be 200k ~ 800k OPs per second, a rwlock is harmful for concurrency as I test before, I think I should reactivate it.
