### ISSUE TITLE
Add extern "C" and more doc

### ISSUE THREAD

**Issue by fordsfords** [tidwall/hashmap.c#39]
Hello Josh, et. al.

I'm going to submit a pull request which adds a conditional extern "C" to hashmap.h, which makes the module more C++ friendly, and adds a section to the README.md "API Notes".

The C++ change may seem odd since most C++ programmers would just use an STL hashmap, but I'm an embedded programmer who has learned the hard way that STL is frequently a bad choice. Better to have a simple C implementation, especially one that can be modified if need be.

The extra doc covers topics that may not be obvious to new users..

Thanks for making this code available.

Pull request coming soon.

Steve

**Comment by tidwall** [comment]
Hi Steve, this change makes sense.
Thanks for the explanation.
