### ISSUE TITLE
Is it possible to have an int as key?

### ISSUE THREAD

**Issue by exislow** [tidwall/hashmap.c#4]
Lets take your example from README.md. I would like to have the age as my key. So I can get the name from the hashmap based on the provided age not the name. What to I need to change in your example code to do so?

This just do not work:
```
uint64_t user_hash(const void *item, uint64_t seed0, uint64_t seed1) {
    const struct user *user = item;
    return hashmap_sip(user->age, strlen(user->age), seed0, seed1);
}
```

**Comment by tidwall** [comment]
Yes, you can hash the int like this.

```
uint64_t user_hash(const void *item, uint64_t seed0, uint64_t seed1) {
    const struct user *user = item;
    return hashmap_sip(&user->age, sizeof(user->age), seed0, seed1);
}
```

**Comment by exislow** [comment]
Thanks, I have not thought of `&`. This is why my solution failed.

Do you actually know a way of a two way lookup? E.g. I would actually like to lookup the item by `user->name` or by `user->age`. Is this somehow possible with your solution (or any other you could recommend)?

**Comment by tidwall** [comment]
I'm not aware of a way to with a single hashmap. Perhaps you can use two hash maps? Add each item in both and store item by name in one and by age in the other. Then for getting the value back, you could look at either one.

**Comment by exislow** [comment]
Thanks.
