### ISSUE TITLE
Usage error

### ISSUE THREAD

**Issue by eriknikulski** [tidwall/hashmap.c#5]
Hi, I would like to use this hashmap but when I run it I get this error:

```bash
dep/hashmap_c/hashmap.c:210:15: error: variable length array used [-Werror,-Wvla]
    char edata[map->bucketsz]; // VLA
```

**Comment by tidwall** [comment]
VLAs are a part of the C99 standard, which compiler are you using?

**Comment by tidwall** [comment]
After looking into it further the VLA could be replaced with a standard allocation.

I pushed an update (v0.3.1). Please try again.

**Comment by eriknikulski** [comment]
Thank you a lot, works perfectly!
