### ISSUE TITLE
[Improvement request] possibility to add destructor for item.

### ISSUE THREAD

**Issue by thetoster** [tidwall/hashmap.c#7]
Even if items are copied into hashmap it might contains some pointers to owned memory. It would be nice to have possibility to define destructor for such items. For example give it at as a param for hashmap_new.
Then:
1) I would change behavior of ```hashmap_delete``` to call destructor on deleted item and return true/false if item was found and deleted.
2) Since ```hashmap_delete``` removes and destroys object new function ```hashmap_detach``` should provide functionality which currently is done via ```hashmap_delete```.

Reasoning.
* Every time I want to delete item I need to detach it via ```hashmap_delete``` and call destructor function on detached item manually, it's very error prone and can be automated. 
* Every time I want to destroy whole hashmap I need to perform ```hashmap_scan``` and call destructors on each item in map, again this creates boilerplate code.

**Comment by tidwall** [comment]
The current implementation makes no assumptions about ownership and right now adding destructors is outside the scope of this library. 

Would it be feasible for you to create a wrapper api around the hashmap library that would meet your specialized ownership rules. For example, let's say you have hashmap that is collection of a type called `person`. You could make `hm_person_new()`, `hm_person_free()`, `hm_person_set()`, `hm_person_delete()` that manage automated destructor logic?

**Comment by thetoster** [comment]
Yes wrappers are one of possible solutions, but they just wrap problem not solve it ;)
I have many different types of "object" stored in hashmap so creating bunch of wrappers is kind a messy. I believe I'll fork and extend this library to have destructor feature. Just need to find some extra free time in project to understand inner structure of your lib.
