### ISSUE TITLE
Not Working With MSVC

### ISSUE THREAD

**Issue by IndianBoy6** [tidwall/hashmap.c#9]
This has been working with GCC for a while but with MSVC there is an error with this line of code (line 121):
```c
    map->edata = map->spare+bucketsz;
```
because map->spare is a raw pointer so you can't do pointer arithmetic. On GCC, the size of raw pointers is assumed to be 1 byte but this isn't the case on MSVC. Changing that line of code to this:
```c
    map->edata = (char*)map->spare+bucketsz;
```
seems to work.

**Comment by tidwall** [comment]
Thanks for letting me know.
